import pandas as pd
import numpy as np

# list generated by ChatGPT
names = [ "Lorenzo", None, "Giulia", "Martina", "Alessio", "Sara", None, "Davide", "Chiara", "Michele", "Elena" ]
cities = [ "Bologna", "Turin", None, "Florence", "Naples", None, "Genoa", "Perugia" ]

size_data = 31

# random dataframe creation
df = pd.DataFrame({
    "Name": np.random.choice(names, size_data),
    "Age": np.random.randint(14, 61, size_data),
    "City": np.random.choice(cities, size_data),
    "Salary": np.random.randint(1600, 3600, size_data),
})

# NaN index for age and salary
for col in ["Age", "Salary"]:
    indici_nan = np.random.choice(df.index, size=3, replace=False)
    df.loc[indici_nan, col] = np.nan

# numeric column filter
numbers = df.select_dtypes(include=["float64", "int64"])

print(df)

# create copy for dataframe modifications
df_copy = df.copy()

# view first 5 rows
print("\n=====FIRST 5 ROWS=====\n")
print(df.head())

# view last 5 rows
print("\n=====LAST 5 ROWS=====\n")
print(df.tail())

# descriptive statistics calculation
print("\n=====DESCRIPTIVE STATISTICS=====\n")
stats = df.describe()
print(stats)

# duplicate removal
print("\n=====DUPLICATE REMOVAL=====\n")
df_copy = df.drop_duplicates()
print(df_copy)

# missing values replaced with the median
print("\n=====REPLACING MISSING VALUES=====\n")
for col in numbers.columns:
    median = df_copy[col].median()
    df_copy[col] = df_copy[col].fillna(median)
    
print(df_copy)

# removing missing values
print("\n=====REMOVING MISSING VALUES=====\n")
df_copy = df_copy.dropna()
print(df_copy)

# adding a column for age classification
print("\n=====ADDING A COLUMN=====\n")
def classify_age(age):
    if age <= 18:
        return "Young"
    elif age <= 45:
        return "Adult"
    else:
        return "Senior"

df_copy["Age Category"] = df_copy["Age"].apply(classify_age)
print(df_copy)

# saving the dataframe to csv
file_path = "python_course/Exercises/Pandas/dataset/work.csv"
df_copy.to_csv(file_path)
